export enum PRODUCT_TYPE {
  FACTORING = 'FACTORING',
  CASH_ADVANCE = 'CASH_ADVANCE',
  CONSOLIDATION = 'CONSOLIDATION',
  CREDIT_CARD = 'CREDIT_CARD',
  CARD_PROCESSOR = 'CARD_PROCESSOR',
  LINE_OF_CREDIT = 'LINE_OF_CREDIT',
}
