export enum REFERRAL_SOURCES {
  ONLINE_AD = 'ONLINE_AD',
  FRIEND = 'FRIEND',
  FAMILY = 'FAMILY',
  TV = 'TV',
  RADIO = 'RADIO',
  NEWSPAPER = 'NEWSPAPER',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  WEBSITE = 'WEBSITE',
  EMAIL_CAMPAIGN = 'EMAIL_CAMPAIGN',
  OTHER = 'OTHER',
}
